### ISSUE TITLE
Use JSBI instead of BigInt until BigInt is widely-supported

### ISSUE THREAD

**Issue by jgonera** [evert/bigint-money#30]
Thanks for this library, great work!

Google Chrome team has a JS-only implementation of `BigInt` for environments that don't support `BigInt` natively yet: https://github.com/GoogleChromeLabs/jsbi

It follows the official spec. They claim its performance is comparable with V8's native implementation and there's a Babel plugin to transform the code to use the native API when it's more widely-available.

Have you seen it / have you considered using it instead?

**Comment by evert** [comment]
I did find this at the time of writing, but wasn't super interested. I wanted to write a library for the future, not the past. A big reason is that there are other libraries available for older platforms.

Besides, we just need Safari support for bigint and then it should work everywhere =)

**Comment by jgonera** [comment]
I understand. I suggested JSBI because it has a clear migration path to native and a 1:1 API mapping. I wish I could use this but I need to support a few recent versions of each browser so while Safari Technology Preview seems to be getting some `BigInt` traction (https://developer.apple.com/safari/technology-preview/release-notes/) it will be a while until nobody uses Safari that doesn't support it.

I might revisit in future though, thanks :)
