### ISSUE TITLE
Publish ES module along with CJS

### ISSUE THREAD

**Issue by itaisteinherz** [evert/bigint-money#33]
First of all, thanks for creating this module! It's been super helpful for me. One thing that would be great to have is the module in ESM version, as I'm using ESM + TS, and would love to use this without having to compile the source code of this library myself.

If you don't have the time to work on this yourself, please let me know. I'm no expert in TS, but I'd be happy to try and work on this.

**Comment by itaisteinherz** [comment]
It seems like some issue with my local configuration broke things, which made me think that the module doesn't support ESM.

**Comment by evert** [comment]
Ok glad you figured it out, and glad you like the lib!
