### ISSUE TITLE
Conversion from 'BigInt' to 'number' is not allowed

### ISSUE THREAD

**Issue by DDushkin** [evert/bigint-money#47]
Hello, thanks for the package, however I have some problems with using it on React Native
<img width="375" alt="Снимок экрана 2022-06-09 в 20 42 32" src="https://user-images.githubusercontent.com/25999628/172910976-2a1b2c43-5633-4df0-8276-b14f7689e11d.png">

I tried to change `"target": "es2020"` in my `tsconfig.json`, but it didn't help

**Comment by evert** [comment]
It looks like this is a runtime error, but it doesn't seem correct... I'm not super familiar with React native, but do you know anything about what kind of V8 / Node engine it runs?

**Comment by DDushkin** [comment]
> It looks like this is a runtime error, but it doesn't seem correct... I'm not super familiar with React native, but do you know anything about what kind of V8 / Node engine it runs?

So far what I found is that problem with Babel auto transforming `**` to `pow()`, and it is failing with BigInt
https://reactnative.dev/docs/javascript-environment
<img width="862" alt="Снимок экрана 2022-06-09 в 21 07 17" src="https://user-images.githubusercontent.com/25999628/172915020-46eb88d8-b387-4798-9082-d510aea1ca6a.png">
https://babeljs.io/docs/en/babel-plugin-transform-exponentiation-operator
and as I undestood it is built in RN

**Comment by evert** [comment]
I see! can you not use Babel, or configure it to not do this conversion?

**Comment by DDushkin** [comment]
Yeah, it seems I found a solution
The problem was in default `metro-react-native-babel-preset` having this plugin `babel-plugin-transform-exponentiation-operator`
So I used this approach to fix the babel config
https://gist.github.com/karanjthakkar/3241808022a75d8068f35a33b57e90c5
