### ISSUE TITLE
The number N is not a "safe" integer. It must be converted before passing it

### ISSUE THREAD

**Issue by DDushkin** [evert/bigint-money#48]
Hello, I have another issue while using your lib, can you take a look?
So I have an wallet app that needs to convert currencies
Here is my code
```tsx
function convertMoney(
    moneyObject: Money,
    currencyName: CurrencyName,
    rates: FiatRates & AssetRates,
) {
    const rate = rates[moneyObject.currency as CurrencyName][currencyName];

    return moneyObject.multiply(rate);
}

const exchangeRates = {
   BTC: { USD: 30161.68359375 },
   ...
}
const assetAmount = new Money(balance, "BTC"); // balance is bigint -> i.e. BigInt(0) now
const fiatAmount = convertMoney(assetAmount, fiatCurrency.code, exchangeRates) //Error: The number 30161.68359375 is not a "safe" integer. It must be converted before passing it
```

And when I try to call this function I get `Error: The number 30161.68359375 is not a "safe" integer. It must be converted before passing it`

**Comment by DDushkin** [comment]
Then I checked your utils and tried to change my rates from float numbers to string like this 
```
const rate = `${rates[moneyObject.currency as CurrencyName][currencyName]}`;
```

But that returns different error ` TypeError: Input string must follow the pattern (-)##.## or -##`

**Comment by DDushkin** [comment]
@evert so it seems that problem is here 
`input.match(/^(-)?([0-9]*)?(\.([0-9]*))?$/)`

However, testing such string `1794.8353271484375` with regex in online tools like https://regex101.com/ returns 4 groups 
<img width="453" alt="Снимок экрана 2022-06-10 в 09 35 14" src="https://user-images.githubusercontent.com/25999628/173005429-6a324d13-6149-4989-802d-522926447e86.png">
But console.log and dev tools console return 5 groups
<img width="456" alt="Снимок экрана 2022-06-10 в 09 37 21" src="https://user-images.githubusercontent.com/25999628/173005650-20cbc50c-db1b-42a4-8e04-ca5b0bc40105.png">
<img width="564" alt="Снимок экрана 2022-06-10 в 09 37 45" src="https://user-images.githubusercontent.com/25999628/173005704-45a4551d-a529-43f0-b2f4-2284f4e6bf64.png">
So that mysterious `undefined` does the error

**Comment by evert** [comment]
I take it you figured it out? Not being able to pass floats is very much by design because it could be indicative of a bug with precision loss.

So by forcing you to call toFixed you're explicitly making this choice.

**Comment by DDushkin** [comment]
> I take it you figured it out? Not being able to pass floats is very much by design because it could be indicative of a bug with precision loss.
> 
> So by forcing you to call toFixed you're explicitly making this choice.

Yeah, I figured out when checked the code more precisely
But now I have problems with float values that are returned from server with exponent, i.e `5.267390861263266e-7`

**Comment by evert** [comment]
Would this work for you?

   (5.267390861263266e-7).toFixed(21)
   
There's no point in adding more digits because this lib will support up to 20 decimals
